{ @author: Sylvain Maltais (support@gladir.com)
  @created: 2023
  @website(https://www.gladir.com/CODER/TPW4TPLIB-TP)
  @abstract(Target: Turbo Pascal 7, Free Pascal 3.2)
}

Unit COLORDLG;

INTERFACE

Const
 dlg_Color=10;
 color_HueScroll=700;
 color_SatScroll=701;
 color_LumScroll=702;
 color_Hue=703;
 color_Sat=704;
 color_Lum=705;
 color_Red=706;
 color_Green=707;
 color_Blue=708;
 color_Current=709;
 color_Rainbow=710;
 color_Save=711;
 color_Add=712;
 color_Solid=713;
 color_Tune=714;
 color_Schemes=715;
 color_Element=716;
 color_Samples=717;
 color_Palette=718;
 color_Mix=719;
 color_Box1=720;
 color_Custom1=721;
 color_HueAccel=723;
 color_SatAccel=724;
 color_LumAccel=725;
 color_RedAccel=726;
 color_GreenAccel=727;
 color_BlueAccel=728;
 num_Basic_Colors=48;
 num_Custom_Colors=16;

IMPLEMENTATION

END.